### ISSUE TITLE
docs/update readme

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr-sks#26]
- update info about requests and responses of API in readme
-  update db schema (look below for the actual one in comments)

**Comment by kamilfedio** [comment]
I will check schema in my docs with actual one in the code

**Comment by kamilfedio** [comment]
![Image](https://github.com/user-attachments/assets/23cfa5a8-ffba-4cb0-b09a-64b57d1c01b0)
One change - ```updated_at``` in hashes_meals is missing
