### ISSUE TITLE
fix/technical messages shown as meals

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr-sks#28]
edit menu scrapper logic to avoid adding technical messages as meals
my first thought is to check if price is !=0, but any other fixes are welcome
also this was the first time something like this happened so we don't have much info about this issue

![Image](https://github.com/user-attachments/assets/60d4b8c7-f3a9-42c5-88cb-1d4bd656e9a5)

**Comment by simon-the-shark** [comment]
That's a good logic - my only note is that we can also use those technical messages as a separate list of messages in the response and we'll show it accordingly

**Comment by kamilfedio** [comment]
Another idea
- if there is no numbers in msg ( i am Not sure if all meals contains numbers - check it) - Not correct msg
- if after numbers is any info Such as ```grams``` ```g```etc - correct msg
- if two numbers exists is ```/``` between them - correct msg
- if is ```:``` between numbers Such us hour - Not corrext msg

I am open to opinions about it

**Comment by simon-the-shark** [comment]
There is also this known edge case:


![image-1.png](https://github.com/user-attachments/assets/32598e4f-9304-4f88-aabc-2a85535cee45)


The data there is basically typed by hand by some lady Grażynka or someone like this, but imo the assumption that if the price is 0 then this is an alert and not a meal is a good guess

**Comment by czaja307** [comment]
> That's a good logic - my only note is that we can also use those technical messages as a separate list of messages in the response and we'll show it accordingly

should we make another table for such messages or creating new "meal" type in the enum is enough?
